/*
 * Copyright 2023 Philipp Salvisberg <philipp.salvisberg@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ch.islandsql.grammar;

import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.Parser;
import org.antlr.v4.runtime.TokenStream;

/**
 * Base class for IslandSqlParser class generated by ANTLR.
 * Used to provide methods to be used as semantic predicates in the parser grammar.
 */
public abstract class IslandSqlParserBase extends Parser {
    /**
     * Constructor
     *
     * @param input The token stream.
     */
    public IslandSqlParserBase(TokenStream input) {
        super(input);
        assert input instanceof CommonTokenStream : "Parser requires a CommonTokenStream as input.";
    }
}
